AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: poja-api - Computation and API

Globals:
  Function:
    CodeUri: .
    Runtime: java21
    Tracing: Active
    Architectures:
      - arm64
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    
    Environment:
      Variables:
        ENV: !Ref Env
        AWS_S3_BUCKET: !Sub '{{resolve:ssm:/poja-api/${Env}/s3/bucket-name}}'
        AWS_SES_SOURCE: noreply@preprod.poja.io
        AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/poja-api/${Env}/eventbridge/bus-name}}'
        AWS_EVENT_STACK_1_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/poja-api/${Env}/1/sqs/mailbox-queue-url}}'
        AWS_EVENT_STACK_2_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/poja-api/${Env}/2/sqs/mailbox-queue-url}}'
        
        
        SENTRY_DSN: !Sub '{{resolve:ssm:/poja-api/sentry/dsn}}'
        SENTRY_ENVIRONMENT: !Ref Env
        GITHUB_CLIENT_ID: !Sub '{{resolve:ssm:/poja-api/${Env}/github/client/id}}'
        GITHUB_CLIENT_SECRET: !Sub '{{resolve:ssm:/poja-api/${Env}/github/client/secret}}'
        GITHUB_REDIRECT_URI: !Sub '{{resolve:ssm:/poja-api/${Env}/github/redirect/uri}}'
        GITHUB_TOKEN_URL: !Sub '{{resolve:ssm:/poja-api/${Env}/github/token/url}}'
        APPS_ENVS_NETWORKING: !Sub '{{resolve:ssm:/poja-api/${Env}/apps/env/networking}}'
        GITHUB_API_BASEURI: !Sub '{{resolve:ssm:/poja-api/${Env}/github/api/base-uri}}'
        GITHUB_APPID: !Sub '{{resolve:ssm:/poja-api/${Env}/github/app/id}}'
        POJA_SAM_API_KEY: !Sub '{{resolve:ssm:/poja-api/${Env}/poja/sam/api/key}}'
        STRIPE_API_KEY: !Sub '{{resolve:ssm:/poja-api/${Env}/stripe-api-key}}'
        PRIVATE_BETA_TEST: !Sub '{{resolve:ssm:/poja-api/${Env}/private-beta-test}}'
        BETA_USERS: !Sub '{{resolve:ssm:/poja-api/${Env}/beta/users}}'
        AWS_ACCOUNT_ID: !Sub '{{resolve:ssm:/poja-api/${Env}/aws/account-id}}'
        POJA_SAM_API_URI: !Sub '{{resolve:ssm:/poja-api/${Env}/poja/sam/api/uri}}'
        SPRING_DATASOURCE_URL: !Sub '{{resolve:ssm:/poja-api/${Env}/db/url}}'
        SPRING_DATASOURCE_USERNAME: !Sub '{{resolve:ssm:/poja-api/${Env}/db/user/username}}'
        SPRING_DATASOURCE_PASSWORD: !Sub '{{resolve:ssm:/poja-api/${Env}/db/user/password}}'
        MAX_APPS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/max/apps/per/user}}'
        BETA_USER_APP_THRESHOLD: !Sub '{{resolve:ssm:/poja-api/${Env}/beta/max/apps/per/user}}'
        BETA_USER_CONSOLE_THRESHOLD: !Sub '{{resolve:ssm:/poja-api/${Env}/beta/max/console/per/org}}'
        BETA_MAX_USER_ORGS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/beta/max/user/orgs/per/user}}'
        E2E_MAX_APPS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/e2e/max/apps/per/user}}'
        MAX_GROUPS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/max/groups/per/user}}'
        E2E_MAX_GROUPS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/e2e/max/groups/per/user}}'
        E2E_USER_ID: !Sub '{{resolve:ssm:/poja-api/${Env}/e2e/user/id}}'
        E2E_USER_MAIN_ORG_ID: !Sub '{{resolve:ssm:/poja-api/${Env}/e2e/user/main/org/id}}'
        MAX_GROUPS_PER_ORG: !Sub '{{resolve:ssm:/poja-api/${Env}/max/groups/per/org}}'
        MAX_ORGS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/max/orgs/per/user}}'
        E2E_MAX_ORGS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/e2e/max/orgs/per/user}}'
        MAX_USERS: !Sub '{{resolve:ssm:/poja-api/${Env}/max/users}}'
        MAX_USERS_PER_ORG: !Sub '{{resolve:ssm:/poja-api/${Env}/max/users/per/org}}'
        MAX_ORG_MEMBERSHIPS_PER_USER: !Sub '{{resolve:ssm:/poja-api/${Env}/max/org/memberships/per/user}}'
        PRICING_FREE_TIER: !Sub '{{resolve:ssm:/poja-api/${Env}/pricing/free/tier}}'
        MAX_PREMIUM_SUBSCRIBERS: !Sub '{{resolve:ssm:/poja-api/${Env}/max/premium/subscribers}}'
        USER_SUSPENSION_GRACE_PERIOD: !Sub '{{resolve:ssm:/poja-api/${Env}/user/suspension/grace/period}}'
        MAX_ALLOWED_INACTIVITY_DAYS: !Sub '{{resolve:ssm:/poja-api/${Env}/max/allowed/inactivity/days}}'
        ORG_APP_INVITATION_BASE_URL: !Sub '{{resolve:ssm:/poja-api/${Env}/org/app/invitation/base/url}}'
        APP_PEM_BUCKET_KEY: !Sub '{{resolve:ssm:/poja-api/${Env}/app/pem/bucket/key}}'
    
        
Parameters:
  Env:
    Type: String

Resources:
  
  FrontalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.poja.io.handler.LambdaHandler::handleRequest
      MemorySize: 1024
      Timeout: 30
      Role: !Sub '{{resolve:ssm:/poja-api/${Env}/execution/role-arn}}'
      
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        
      ReservedConcurrentExecutions: 50

  WorkerFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.poja.io.handler.MailboxEventHandler::handleRequest
      MemorySize: 1124
      Timeout: 600 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/poja-api/${Env}/execution/role-arn}}'
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/poja-api/${Env}/1/sqs/mailbox-queue-arn}}'
            BatchSize: 5
      ReservedConcurrentExecutions: 50

  WorkerFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.poja.io.handler.MailboxEventHandler::handleRequest
      MemorySize: 1100
      Timeout: 600 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/poja-api/${Env}/execution/role-arn}}'
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/poja-api/${Env}/2/sqs/mailbox-queue-arn}}'
            BatchSize: 1
      ReservedConcurrentExecutions: 15

  ApiUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /poja-api/, !Ref Env, /api/url ] ]
      Type: String
      Value: !GetAtt FrontalFunctionUrl.FunctionUrl
  
Outputs:
  ApiUrl:
    Description: Url to access the frontal function
    Value: !GetAtt FrontalFunctionUrl.FunctionUrl
        
